version: '3.9'

services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - DB_CONNECT=testdb
      - PORT=3000
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:5001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.17.14
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=testpassword
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data:
